# 1. إعدادات اسم وتطبيقات السيرفر
spring.application.name=tp-13
server.port=8086

spring.security.oauth2.client.registration.keycloak.client-id=spring-oauth-client

spring.security.oauth2.client.registration.keycloak.client-secret=GdkZgY0rbFMIx0h9vfLFOTI8oe5J0boQ

spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email

spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8081/realms/ens-realm

logging.level.org.springframework.security=DEBUG